#!/usr/bin/env sh

cmd_run() {
    arg="$1"
    if [ -z "$arg" ] ; then
        path=$(ls src/bin | tail -1)
        name=${path%.rs}
        cargo run --release --bin $name
        exit
    fi
    if case $arg in -*) true;; *) false;; esac; then
        path=$(ls src/bin | tail $arg | head -n 1)
        name=${path%.rs}
        cargo run --release --bin $name
        exit
    fi
    name="$arg"
    cargo run --release --bin $name
}

cmd_new() {
    cd src/bin
    new="$(date +%F-%H-%M-%S).rs"
    touch "$new"
    cd ../..
    code "./src/bin/$new"
}

cmd_copy() {
    arg="$1"
    if [ -z "$arg" ] ; then
        cd src/bin
        path=$(ls | tail -1)
        new="$(date +%F-%H-%M-%S).rs"
        cp "$path" "$new"
        cd ../..
        code "./src/bin/$new"
        exit
    fi
    if case $arg in -*) true;; *) false;; esac; then
        cd src/bin
        path=$(ls | tail $arg | head -n 1)
        new="$(date +%F-%H-%M-%S).rs"
        cp "$path" "$new"
        cd ../..
        code "./src/bin/$new"
        exit
    else
        cd src/bin
        path=${arg%.rt}
        new="$(date +%F-%H-%M-%S).rs"
        cp "$path.rs" "$new"
        cd ../..
        code "./src/bin/$new"
        exit
    fi
    
}

cmd_save() {
    git add .
    git commit -m "-"
    git push
}

cmd_help() {
    cat << EOF
usage: luna <command>
commands:
    run | r
    new | n
    copy | c
    save | s
    help
EOF
}

main() {
    cmd="$1"
    if [ -z "$cmd" ] ; then
        cmd_help
        exit
    fi
    shift > /dev/null 2>&1
    case "$cmd" in
        run|r )
            cmd_run $@;;
        new|n )
            cmd_new $@;;
        copy|c )
            cmd_copy $@;;
        save|s )
            cmd_save $@;;
        help|* )
            cmd_help $@;;
    esac
}

main $@
